"""
Quantum Physics Module

Provides quantum system modeling, simulation, and analysis.

Core Modules:
- states: Quantum state representations (Ket, Bra, DensityMatrix)
- hamiltonian: Hamiltonian operators and quantization
- solver: Schrodinger equation solvers
- simulator: Simulation frameworks
- interactive: SceneBuilder for arbitrary scenarios
- analysis: Symmetry analysis and result interpretation

Integrates with abstract_phys module for symmetry operations,
generators, and physical system frameworks.
"""

from .analysis import (
    AnalysisResult,
    GroupRepresentation,
    GroupTheoryAnalyzer,
    LieAlgebra,
    QuantumAnalyzer,
    QuantumParityOperation,
    QuantumSymmetryOperation,
    QuantumTranslationOperation,
    SO3LieAlgebra,
    SO4HydrogenAnalyzer,
    StateClassification,
    SU2LieAlgebra,
    SymmetryInfo,
    TransitionRule,
    analyze,
    analyze_group_theory,
    check_parity,
    detect_hydrogen_so4_symmetry,
    quick_report,
    tensor_operator_matrix_element,
    wigner_eckart_coupling,
)
from .explainer import (
    CompositeExplainer,
    DecoherenceExplainer,
    DynamicsExplainer,
    EnergySpectrumExplainer,
    MeasurementExplainer,
    QuantumStateExplainer,
    ResultExplainer,
    SymmetryExplainer,
    explain_measurement_results,
    explain_quantum_system,
)
from .hamiltonian import (
    CanonicalQuantizer,
    FreeParticleHamiltonian,
    HamiltonianBuilder,
    HamiltonianOperator,
    HarmonicOscillatorHamiltonian,
    HydrogenAtomHamiltonian,
    MatrixHamiltonian,
    PerturbationHamiltonian,
    SpinHamiltonian,
    angular_momentum_operators,
    from_quantum_system,
    pauli_matrices,
    spin_operators,
)
from .hydrogen_symmetry import (
    AngularMomentumOperator,
    HydrogenSO4Symmetry,
    HydrogenSymmetryAnalyzer,
    RungeLenzVector,
    SO4Generators,
    analyze_hydrogen_symmetry,
    create_hydrogen_so4_analyzer,
)
from .integration import (
    GroupRepresentationBridge,
    LieAlgebraToQuantumBridge,
    QuantumToAbstractBridge,
    SymmetryToQuantumBridge,
    create_quantum_from_abstract,
    export_to_abstract_phys,
    integrate_with_abstract_phys,
    quick_bridge,
    quick_lie_bridge,
)
from .interactive import (
    Particle,
    Potential,
    QuantumScene,
    SceneBuilder,
    SceneHamiltonianBuilder,
    SceneSymmetryAnalyzer,
    SimulationResult,
    Visualizer,
    analyze_scene_symmetry,
    quick_simulate,
    simulate,
)
from .simulator import (
    DecoherenceSimulator,
    MeasurementSimulator,
    ParticleFieldSimulator,
    QuantumSimulator,
    ScatteringSimulator,
    Simulator,
    SpinChainSimulator,
    create_simulation,
)
from .solver import (
    ExactDiagonalizationSolver,
    HarmonicOscillatorSolver,
    HydrogenAtomSolver,
    LanczosSolver,
    NumerovSolver,
    ParticleInBoxSolver,
    QuantumSolverFactory,
    Solver,
    SparseMatrixSolver,
    SplitStepFourierSolver,
    TimeEvolutionSolver,
    VariationalSolver,
    compute_spectrum,
    solve_schrodinger,
    time_evolve,
)
from .states import (
    Bra,
    DensityMatrix,
    Ket,
    QuantumState,
    StateVector,
    basis_state,
    bell_state,
    ghz_state,
    superposition,
    tensor_product,
    w_state,
)

__all__ = [
    # States
    "QuantumState",
    "Ket",
    "Bra",
    "StateVector",
    "DensityMatrix",
    "basis_state",
    "bell_state",
    "w_state",
    "ghz_state",
    "tensor_product",
    "superposition",
    # Hamiltonian
    "HamiltonianOperator",
    "MatrixHamiltonian",
    "FreeParticleHamiltonian",
    "HarmonicOscillatorHamiltonian",
    "SpinHamiltonian",
    "HydrogenAtomHamiltonian",
    "PerturbationHamiltonian",
    "CanonicalQuantizer",
    "HamiltonianBuilder",
    "pauli_matrices",
    "spin_operators",
    "angular_momentum_operators",
    "from_quantum_system",
    # Solvers
    "Solver",
    "ExactDiagonalizationSolver",
    "SparseMatrixSolver",
    "LanczosSolver",
    "TimeEvolutionSolver",
    "SplitStepFourierSolver",
    "VariationalSolver",
    "NumerovSolver",
    "solve_schrodinger",
    "time_evolve",
    "compute_spectrum",
    "QuantumSolverFactory",
    "HydrogenAtomSolver",
    "HarmonicOscillatorSolver",
    "ParticleInBoxSolver",
    # Simulators
    "Simulator",
    "QuantumSimulator",
    "MeasurementSimulator",
    "DecoherenceSimulator",
    "ParticleFieldSimulator",
    "ScatteringSimulator",
    "SpinChainSimulator",
    "create_simulation",
    # Interactive
    "Particle",
    "Potential",
    "QuantumScene",
    "SceneBuilder",
    "SceneHamiltonianBuilder",
    "SceneSymmetryAnalyzer",
    "simulate",
    "SimulationResult",
    "Visualizer",
    "quick_simulate",
    "analyze_scene_symmetry",
    # Analysis
    "QuantumAnalyzer",
    "QuantumSymmetryOperation",
    "QuantumParityOperation",
    "QuantumTranslationOperation",
    "SymmetryInfo",
    "StateClassification",
    "TransitionRule",
    "AnalysisResult",
    "analyze",
    "quick_report",
    "check_parity",
    "GroupRepresentation",
    "LieAlgebra",
    "SO3LieAlgebra",
    "SU2LieAlgebra",
    "GroupTheoryAnalyzer",
    "analyze_group_theory",
    "wigner_eckart_coupling",
    "tensor_operator_matrix_element",
    "SO4HydrogenAnalyzer",
    "detect_hydrogen_so4_symmetry",
    # Hydrogen SO4 Symmetry
    "HydrogenSymmetryAnalyzer",
    "HydrogenSO4Symmetry",
    "SO4Generators",
    "RungeLenzVector",
    "AngularMomentumOperator",
    "analyze_hydrogen_symmetry",
    "create_hydrogen_so4_analyzer",
    # Explainer
    "ResultExplainer",
    "EnergySpectrumExplainer",
    "QuantumStateExplainer",
    "DynamicsExplainer",
    "MeasurementExplainer",
    "DecoherenceExplainer",
    "CompositeExplainer",
    "SymmetryExplainer",
    "explain_quantum_system",
    "explain_measurement_results",
    # Integration with core and abstract_phys
    "QuantumToAbstractBridge",
    "SymmetryToQuantumBridge",
    "LieAlgebraToQuantumBridge",
    "GroupRepresentationBridge",
    "integrate_with_abstract_phys",
    "create_quantum_from_abstract",
    "export_to_abstract_phys",
    "quick_bridge",
    "quick_lie_bridge",
]
